package com.amazon.aws.pix.core.http;

/**
 * Decides what to do with an inbound request that carries a {@code Content-Encoding}.
 *
 * <h2>Why rejecting is the correct behaviour, not merely the safe one</h2>
 *
 * <p>The BCB DICT API documentation recommends callers send {@code Accept-Encoding: gzip} so that
 * <em>responses</em> may be compressed, and states that sending a compressed <em>request</em> is not
 * supported. So a compressed request body is something BCB itself will not accept.
 *
 * <p>What the proxy used to do with one was worse than forwarding it. The route converted the body
 * to a String and then signed it, so gzip bytes became mojibake — the gzip magic {@code 0x1f 0x8b}
 * maps to {@code 31, U+FFFD} through a charset decode, irreversibly — and the proxy then produced a
 * <b>valid XML signature over that corrupted document</b> and sent it to BCB under the PSP's own
 * key. The signature would verify; the content would be garbage. A PSP signing nonsense is a worse
 * outcome than a rejected request, and it is the kind of thing that is very hard to explain after
 * the fact.
 *
 * <p>Note that this cannot be fixed by decoding the request instead. Decoding would produce a body
 * BCB has said it will not accept, so the proxy would be silently rewriting a client's request into
 * a different one — and the signature would then cover bytes the client never sent. Rejecting keeps
 * the proxy honest about what it signs.
 *
 * <h2>Status code</h2>
 *
 * <p>415, per RFC 7231's treatment of an unsupported {@code Content-Encoding}. This rejection is
 * generated by the proxy about what the proxy is willing to sign, so it is deliberately not one of
 * the DICT error statuses — nothing was sent to BCB, and presenting a DICT error would suggest BCB
 * had answered.
 */
public final class CompressedRequestPolicy {

    /** RFC 7231: the appropriate status for a Content-Encoding the server will not accept. */
    public static final int REJECTION_STATUS = 415;

    private CompressedRequestPolicy() {
    }

    /**
     * @param contentEncoding the request's {@code Content-Encoding} header, may be {@code null}
     * @return {@code true} when the request must be refused rather than signed
     */
    public static boolean mustReject(final String contentEncoding) {
        // Reuses the same token parsing the response decoder uses, so "identity", an empty value
        // and absent are all treated as uncompressed by one shared rule rather than two that can
        // drift apart.
        return HttpContentDecoder.isEncoded(contentEncoding);
    }

    /** Explains the refusal to the caller without echoing anything attacker-controlled verbatim. */
    public static String rejectionMessage(final String contentEncoding) {
        final String token = contentEncoding == null ? "" : contentEncoding.trim();
        final String safe = token.length() > 64 ? token.substring(0, 64) + "..." : token;
        return "Compressed request bodies are not supported by the BCB DICT API, so this proxy "
                + "will not sign one. Resend the request uncompressed, without a Content-Encoding "
                + "header. Rejected Content-Encoding: '" + safe.replaceAll("[^\\x20-\\x7E]", "?")
                + "'";
    }
}
